In [12]:
import  DLFramework.Tensor as Tensor
#测试Tensor
x = Tensor([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [8]:
from  DLFramework.Tensor import Tensor
import numpy as np
#测试Tensor 的反向传播
x = Tensor([1,2,3,4,5])
y = Tensor([2,2,2,2,2])
z = x + y

z.backward(Tensor(np.array([1,1,1,1,1])))
print(z)
print(x.grad)
print(y.grad)
print(z.creators)
print(z.creation_op)

[3 4 5 6 7]
[1 1 1 1 1]
[1 1 1 1 1]
[array([1, 2, 3, 4, 5]), array([2, 2, 2, 2, 2])]
add


In [4]:
from  DLFramework.Tensor import Tensor
import numpy as np
a = Tensor([1,2,3,4,5], autograd=True)
b = Tensor([2,2,2,2,2], autograd=True)
c = Tensor([5,4,3,2,1], autograd=True)
d = a + b
e = b + c
f = d + e
f.backward(Tensor(np.array([1,1,1,1,1])))
print(b.grad)

[2 2 2 2 2]
